import { WeatherData, LocationInfo } from '../types/weather';
import palaceSquareImg from '../assets/images/spb_palace_square_1790860395614.jpg';
import vasilievskySpitImg from '../assets/images/spb_vasilievsky_spit_1790860409680.jpg';
import peterPaulFortressImg from '../assets/images/spb_peter_paul_fortress_1790860421562.jpg';
import kronstadtCathedralImg from '../assets/images/spb_kronstadt_cathedral_1790860433524.jpg';
import peterhofPalaceImg from '../assets/images/spb_peterhof_palace_1790860447908.jpg';
import sestroretskCoastImg from '../assets/images/spb_sestroretsk_coast_1790860458447.jpg';
import primorskyLakhtaImg from '../assets/images/spb_primorsky_lakhta_1790860910347.jpg';
import saranskCathedralImg from '../assets/images/saransk_cathedral_1790884199173.jpg';
import moscowRedSquareImg from '../assets/images/moscow_red_square_1790884343471.jpg';
import kazanKremlinImg from '../assets/images/kazan_kremlin_1790884358985.jpg';
import sochiMarineCoastImg from '../assets/images/sochi_marine_coast_1790884373122.jpg';

export const SARANSK_LOCATION: LocationInfo = {
  name: 'Саранск',
  district: 'Республика Мордовия',
  landmark: 'Кафедральный собор св. Феодора Ушакова и Соборная площадь',
  country: 'Россия',
  latitude: 54.1838,
  longitude: 45.1749,
  timezone: 'Europe/Moscow',
  imageUrl: saranskCathedralImg,
};

export const MOSCOW_LOCATION: LocationInfo = {
  name: 'Москва',
  district: 'Центральный ФО',
  landmark: 'Красная площадь, Кремль и Храм Василия Блаженного',
  country: 'Россия',
  latitude: 55.7558,
  longitude: 37.6173,
  timezone: 'Europe/Moscow',
  imageUrl: moscowRedSquareImg,
};

export const KAZAN_LOCATION: LocationInfo = {
  name: 'Казань',
  district: 'Республика Татарстан',
  landmark: 'Казанский Кремль и мечеть Кул-Шариф',
  country: 'Россия',
  latitude: 55.7961,
  longitude: 49.1064,
  timezone: 'Europe/Moscow',
  imageUrl: kazanKremlinImg,
};

export const SOCHI_LOCATION: LocationInfo = {
  name: 'Сочи',
  district: 'Черноморское побережье',
  landmark: 'Морской вокзал Сочи и вид на Кавказские горы',
  country: 'Россия',
  latitude: 43.6028,
  longitude: 39.7342,
  timezone: 'Europe/Moscow',
  imageUrl: sochiMarineCoastImg,
};

export const SPB_LOCATIONS: LocationInfo[] = [
  {
    name: 'Санкт-Петербург',
    district: 'Центральный (Дворцовая)',
    landmark: 'Дворцовая площадь и Зимний дворец',
    country: 'Россия',
    latitude: 59.9386,
    longitude: 30.3141,
    timezone: 'Europe/Moscow',
    imageUrl: palaceSquareImg,
  },
  {
    name: 'Приморский район',
    district: 'Лахта & Парк 300-летия',
    landmark: 'Лахта Центр и побережье Парка 300-летия СПб',
    country: 'Россия',
    latitude: 59.9870,
    longitude: 30.1770,
    timezone: 'Europe/Moscow',
    imageUrl: primorskyLakhtaImg,
  },
  {
    name: 'Васильевский остров',
    district: 'Стрелка В.О. & Залив',
    landmark: 'Стрелка Васильевского острова и Ростральные колонны',
    country: 'Россия',
    latitude: 59.9405,
    longitude: 30.2747,
    timezone: 'Europe/Moscow',
    imageUrl: vasilievskySpitImg,
  },
  {
    name: 'Петроградская сторона',
    district: 'Петропавловская крепость',
    landmark: 'Петропавловская крепость и собор над Невой',
    country: 'Россия',
    latitude: 59.9600,
    longitude: 30.3080,
    timezone: 'Europe/Moscow',
    imageUrl: peterPaulFortressImg,
  },
  {
    name: 'Кронштадт',
    district: 'Остров Котлин / Форты',
    landmark: 'Морской Никольский собор и гавань Кронштадта',
    country: 'Россия',
    latitude: 59.9934,
    longitude: 29.7690,
    timezone: 'Europe/Moscow',
    imageUrl: kronstadtCathedralImg,
  },
  {
    name: 'Петергоф',
    district: 'Финский залив & Парки',
    landmark: 'Большой Петергофский дворец и фонтанный каскад',
    country: 'Россия',
    latitude: 59.8800,
    longitude: 29.9000,
    timezone: 'Europe/Moscow',
    imageUrl: peterhofPalaceImg,
  },
  {
    name: 'Сестрорецк',
    district: 'Курортный район',
    landmark: 'Побережье Финского залива и дюны Сестрорецка',
    country: 'Россия',
    latitude: 60.0988,
    longitude: 29.9676,
    timezone: 'Europe/Moscow',
    imageUrl: sestroretskCoastImg,
  },
  {
    name: 'Саранск',
    district: 'Столица Мордовии',
    landmark: 'Кафедральный собор св. Феодора Ушакова и Соборная площадь',
    country: 'Россия',
    latitude: 54.1838,
    longitude: 45.1749,
    timezone: 'Europe/Moscow',
    imageUrl: saranskCathedralImg,
  },
];

export const ALL_KNOWN_LOCATIONS: LocationInfo[] = [
  ...SPB_LOCATIONS,
  MOSCOW_LOCATION,
  KAZAN_LOCATION,
  SOCHI_LOCATION,
  SARANSK_LOCATION,
];

export const fallbackSpbWeather: WeatherData = {
  location: SPB_LOCATIONS[0],
  current: {
    time: new Date().toISOString(),
    temperature: 9,
    apparentTemperature: 6,
    relativeHumidity: 78,
    weatherCode: 2,
    weatherText: 'Переменная облачность',
    windSpeed: 4.8,
    windDirection: 250, // WSW
    windGusts: 8.5,
    surfacePressure: 1013,
    pressureMmHg: 760,
    uvIndex: 2,
    precipitation: 0.1,
    isDay: true,
    cloudCover: 65,
  },
  hourly: [
    { time: '00:00', hourFormatted: '00:00', temperature: 7, apparentTemperature: 4, weatherCode: 3, weatherText: 'Пасмурно', precipitationProbability: 15, precipitation: 0, windSpeed: 4.1, humidity: 82, isDay: false },
    { time: '02:00', hourFormatted: '02:00', temperature: 6, apparentTemperature: 3, weatherCode: 3, weatherText: 'Пасмурно', precipitationProbability: 20, precipitation: 0, windSpeed: 4.3, humidity: 84, isDay: false },
    { time: '04:00', hourFormatted: '04:00', temperature: 6, apparentTemperature: 3, weatherCode: 45, weatherText: 'Дымка над Невой', precipitationProbability: 20, precipitation: 0, windSpeed: 3.8, humidity: 86, isDay: false },
    { time: '06:00', hourFormatted: '06:00', temperature: 6, apparentTemperature: 3, weatherCode: 2, weatherText: 'Переменная облачность', precipitationProbability: 15, precipitation: 0, windSpeed: 3.9, humidity: 85, isDay: false },
    { time: '08:00', hourFormatted: '08:00', temperature: 7, apparentTemperature: 4, weatherCode: 2, weatherText: 'Переменная облачность', precipitationProbability: 15, precipitation: 0, windSpeed: 4.2, humidity: 81, isDay: true },
    { time: '10:00', hourFormatted: '10:00', temperature: 8, apparentTemperature: 5, weatherCode: 1, weatherText: 'Преимущественно ясно', precipitationProbability: 10, precipitation: 0, windSpeed: 4.6, humidity: 76, isDay: true },
    { time: '12:00', hourFormatted: '12:00', temperature: 10, apparentTemperature: 7, weatherCode: 2, weatherText: 'Переменная облачность', precipitationProbability: 20, precipitation: 0, windSpeed: 5.0, humidity: 70, isDay: true },
    { time: '14:00', hourFormatted: '14:00', temperature: 11, apparentTemperature: 8, weatherCode: 61, weatherText: 'Небольшой дождь', precipitationProbability: 45, precipitation: 0.4, windSpeed: 5.4, humidity: 73, isDay: true },
    { time: '16:00', hourFormatted: '16:00', temperature: 10, apparentTemperature: 7, weatherCode: 61, weatherText: 'Кратковременный дождь', precipitationProbability: 40, precipitation: 0.3, windSpeed: 5.1, humidity: 75, isDay: true },
    { time: '18:00', hourFormatted: '18:00', temperature: 9, apparentTemperature: 6, weatherCode: 2, weatherText: 'Переменная облачность', precipitationProbability: 25, precipitation: 0, windSpeed: 4.7, humidity: 77, isDay: true },
    { time: '20:00', hourFormatted: '20:00', temperature: 8, apparentTemperature: 5, weatherCode: 3, weatherText: 'Пасмурно', precipitationProbability: 20, precipitation: 0, windSpeed: 4.4, humidity: 80, isDay: false },
    { time: '22:00', hourFormatted: '22:00', temperature: 7, apparentTemperature: 4, weatherCode: 3, weatherText: 'Пасмурно', precipitationProbability: 15, precipitation: 0, windSpeed: 4.0, humidity: 83, isDay: false },
  ],
  daily: [
    {
      date: '2026-10-01',
      dayName: 'Сегодня',
      fullDayName: 'Сегодня (Четверг)',
      dateFormatted: '1 окт',
      weatherCode: 2,
      weatherText: 'Переменная облачность',
      tempMax: 11,
      tempMin: 6,
      apparentTempMax: 8,
      apparentTempMin: 3,
      precipitationProbability: 45,
      precipitationSum: 0.7,
      windSpeedMax: 5.4,
      windDirection: 250,
      uvIndexMax: 2,
      sunrise: '07:08',
      sunset: '18:42',
    },
    {
      date: '2026-10-02',
      dayName: 'Пт',
      fullDayName: 'Пятница',
      dateFormatted: '2 окт',
      weatherCode: 61,
      weatherText: 'Небольшой дождь',
      tempMax: 10,
      tempMin: 5,
      apparentTempMax: 7,
      apparentTempMin: 2,
      precipitationProbability: 65,
      precipitationSum: 3.2,
      windSpeedMax: 6.8,
      windDirection: 270,
      uvIndexMax: 1,
      sunrise: '07:11',
      sunset: '18:39',
    },
    {
      date: '2026-10-03',
      dayName: 'Сб',
      fullDayName: 'Суббота',
      dateFormatted: '3 окт',
      weatherCode: 3,
      weatherText: 'Пасмурно',
      tempMax: 9,
      tempMin: 4,
      apparentTempMax: 6,
      apparentTempMin: 1,
      precipitationProbability: 30,
      precipitationSum: 0.2,
      windSpeedMax: 5.2,
      windDirection: 290,
      uvIndexMax: 2,
      sunrise: '07:13',
      sunset: '18:36',
    },
    {
      date: '2026-10-04',
      dayName: 'Вс',
      fullDayName: 'Воскресенье',
      dateFormatted: '4 окт',
      weatherCode: 1,
      weatherText: 'Малооблачно, солнце',
      tempMax: 12,
      tempMin: 4,
      apparentTempMax: 10,
      apparentTempMin: 2,
      precipitationProbability: 10,
      precipitationSum: 0.0,
      windSpeedMax: 3.9,
      windDirection: 220,
      uvIndexMax: 3,
      sunrise: '07:16',
      sunset: '18:33',
    },
    {
      date: '2026-10-05',
      dayName: 'Пн',
      fullDayName: 'Понедельник',
      dateFormatted: '5 окт',
      weatherCode: 63,
      weatherText: 'Дождь над Невой',
      tempMax: 9,
      tempMin: 5,
      apparentTempMax: 6,
      apparentTempMin: 2,
      precipitationProbability: 80,
      precipitationSum: 6.4,
      windSpeedMax: 7.5,
      windDirection: 240,
      uvIndexMax: 1,
      sunrise: '07:18',
      sunset: '18:30',
    },
    {
      date: '2026-10-06',
      dayName: 'Вт',
      fullDayName: 'Вторник',
      dateFormatted: '6 окт',
      weatherCode: 2,
      weatherText: 'Переменная облачность',
      tempMax: 11,
      tempMin: 6,
      apparentTempMax: 9,
      apparentTempMin: 3,
      precipitationProbability: 35,
      precipitationSum: 0.8,
      windSpeedMax: 5.6,
      windDirection: 260,
      uvIndexMax: 2,
      sunrise: '07:21',
      sunset: '18:27',
    },
    {
      date: '2026-10-07',
      dayName: 'Ср',
      fullDayName: 'Среда',
      dateFormatted: '7 окт',
      weatherCode: 3,
      weatherText: 'Облачно с прояснениями',
      tempMax: 10,
      tempMin: 5,
      apparentTempMax: 7,
      apparentTempMin: 2,
      precipitationProbability: 25,
      precipitationSum: 0.1,
      windSpeedMax: 4.8,
      windDirection: 280,
      uvIndexMax: 2,
      sunrise: '07:23',
      sunset: '18:24',
    },
  ],
  updatedAt: 'Только что',
};
